### ISSUE TITLE
Zero w

### ISSUE THREAD

**Issue by MrLately** [arm358/Raspberry-Pi-Automated-WiFi-Access-Point#2]
Latest raspberry pi os lite 32 bit.

Install seemed to go fine but upon reboot it just connected back to my home wifi and I don't see the ssid I programmed during the install.

**Comment by 306bobby-android** [comment]
The pi needs an ethernet port

**Comment by arm358** [comment]
needs to have ethernet port as said before. If you use a usb to ethernet adapter it might work.
