### ISSUE TITLE
Extra setup for hostapd

### ISSUE THREAD

**Issue by actraiser30** [arm358/Raspberry-Pi-Automated-WiFi-Access-Point#4]
Hello great script can you add some extras in hostapd.conf

wmm_enabled=1
ieee80211n=1

Thanks

**Comment by arm358** [comment]
i think both of those settings are enabled by default in hostapd.

**Comment by actraiser30** [comment]
No they are not, I had to put them manually in hostapd,by default 54mbps is enabled only.

Thanks

**Comment by actraiser30** [comment]
You forgot to add them I see,I told you they are missing and required for the hotspot to work correct, unless you don't care...
